/**
 * Pure helpers for Transport monthly summary email / period keys.
 * No Supabase / Resend imports — safe for node tests.
 */

export type TransportMonthlyConsigneeRow = {
  consignee: string;
  loadingWeight: number;
  lrCount: number;
};

export type TransportMonthlySummary = {
  periodFrom: string;
  periodToExclusive: string;
  periodLabel: string;
  totalLrs: number;
  totalLoadingWeight: number;
  uniqueVehicles: number;
  topConsignees: TransportMonthlyConsigneeRow[];
};

/** Calendar month window: [year-month-01, next-month-01). */
export function transportMonthBounds(
  year: number,
  month1to12: number,
): { from: string; toExclusive: string; periodKey: string; periodLabel: string } {
  if (!Number.isInteger(year) || year < 2000 || year > 2100) {
    throw new Error("Invalid year");
  }
  if (!Number.isInteger(month1to12) || month1to12 < 1 || month1to12 > 12) {
    throw new Error("Invalid month");
  }

  const from = `${year}-${String(month1to12).padStart(2, "0")}-01`;
  const nextYear = month1to12 === 12 ? year + 1 : year;
  const nextMonth = month1to12 === 12 ? 1 : month1to12 + 1;
  const toExclusive = `${nextYear}-${String(nextMonth).padStart(2, "0")}-01`;
  const periodKey = `${year}-${String(month1to12).padStart(2, "0")}`;

  const label = new Date(Date.UTC(year, month1to12 - 1, 1)).toLocaleString("en-IN", {
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });

  return { from, toExclusive, periodKey, periodLabel: label };
}

/** Previous completed calendar month relative to an IST "today" date string YYYY-MM-DD. */
export function previousCalendarMonth(todayYmd: string): { year: number; month: number } {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(todayYmd.trim());
  if (!match) throw new Error("Invalid date");
  const year = Number(match[1]);
  const month = Number(match[2]);
  if (month === 1) return { year: year - 1, month: 12 };
  return { year, month: month - 1 };
}

export function formatWeightMt(value: number): string {
  const n = Number.isFinite(value) ? value : 0;
  return `${n.toLocaleString("en-IN", { maximumFractionDigits: 3 })} MT`;
}

export function buildTransportMonthlyEmailText(summary: TransportMonthlySummary): string {
  const lines: string[] = [
    "TRANSPORT MONTHLY SUMMARY",
    summary.periodLabel,
    "",
    `Total LRs: ${summary.totalLrs}`,
    `Total Loading Weight: ${formatWeightMt(summary.totalLoadingWeight)}`,
    `Unique Vehicles: ${summary.uniqueVehicles}`,
    "",
    "Top Consignees",
    "",
  ];

  if (summary.topConsignees.length === 0) {
    lines.push("(No consignee data for this period)");
  } else {
    summary.topConsignees.forEach((row, index) => {
      lines.push(
        `${index + 1}. ${row.consignee} — ${formatWeightMt(row.loadingWeight)} (${row.lrCount} LR${row.lrCount === 1 ? "" : "s"})`,
      );
    });
  }

  lines.push("");
  lines.push("Generated by Transjit ERP — Transport monthly summary.");
  return lines.join("\n");
}

export function mapTransportMonthlySummaryRpc(data: Record<string, unknown>): TransportMonthlySummary {
  const from = String(data.period_from ?? "");
  const toExclusive = String(data.period_to_exclusive ?? "");
  const fromParts = from.split("-").map(Number);
  const year = fromParts[0] ?? 0;
  const month = fromParts[1] ?? 1;
  const bounds = transportMonthBounds(year, month);

  const rawTop = Array.isArray(data.top_consignees) ? data.top_consignees : [];
  const topConsignees: TransportMonthlyConsigneeRow[] = rawTop.map((item) => {
    const row = item as Record<string, unknown>;
    return {
      consignee: String(row.consignee ?? "Unknown"),
      loadingWeight: Number(row.loading_weight ?? 0),
      lrCount: Number(row.lr_count ?? 0),
    };
  });

  return {
    periodFrom: from,
    periodToExclusive: toExclusive,
    periodLabel: bounds.periodLabel,
    totalLrs: Number(data.total_lrs ?? 0),
    totalLoadingWeight: Number(data.total_loading_weight ?? 0),
    uniqueVehicles: Number(data.unique_vehicles ?? 0),
    topConsignees,
  };
}
