import { validateBillingParty, BILLING_PARTY_STATUS_OPTIONS, type BillingPartyMaster } from "./billingParty.schema";
import type { BillingPartyRecord } from "@/components/services/billingParty.service";

/**
 * The exact Billing Party Master columns, in the same order/labels already
 * used by BillingPartyListPage.tsx's existing CSV Export (`handleExport`),
 * plus the module's other own fields (PO Number, Concern Person, Short
 * Code, Payment Cycle Days) that the Add/Edit form already collects. No
 * field is invented here.
 */
export const BILLING_PARTY_TEMPLATE_HEADERS = [
  "Code",
  "Name",
  "GST",
  "Mobile",
  "Email",
  "City",
  "Address",
  "Status",
  "PO Number",
  "Concern Person",
  "Short Code",
  "Payment Cycle Days",
] as const;

type TemplateHeader = (typeof BILLING_PARTY_TEMPLATE_HEADERS)[number];

/** One realistic example row for the "Sample" sheet. `Code` is left
 * blank, matching the existing Add Billing Party form: `code` is never
 * manually typed anywhere in this app — it's auto-generated by
 * `createBillingParty()` (see billingParty.service.ts) when left blank. */
const SAMPLE_ROW: Record<TemplateHeader, string> = {
  Code: "",
  Name: "Sample Logistics Pvt Ltd",
  GST: "27AAAAA0000A1Z5",
  Mobile: "9876543210",
  Email: "accounts@samplelogistics.com",
  City: "Mumbai",
  Address: "123, Industrial Estate, Andheri",
  Status: "Active",
  "PO Number": "PO-2026-001",
  "Concern Person": "Rahul Sharma",
  "Short Code": "SAMP",
  "Payment Cycle Days": "30",
};

export interface BillingPartyUploadRow {
  /** 1-based row number as it appears in the Excel sheet (row 1 is the header). */
  excelRow: number;
  values: BillingPartyMaster;
}

export interface BillingPartyUploadRowError {
  excelRow: number;
  messages: string[];
}

export interface BillingPartyUploadParseResult {
  rows: BillingPartyUploadRow[];
  errors: BillingPartyUploadRowError[];
}

function cellToString(value: unknown): string {
  if (value == null) return "";

  if (typeof value === "object") {
    const text = (value as { text?: unknown }).text;
    if (typeof text === "string") return text.trim();

    const result = (value as { result?: unknown }).result;
    if (result != null) return String(result).trim();

    return "";
  }

  return String(value).trim();
}

function writeHeaderRow(sheet: import("exceljs").Worksheet) {
  sheet.columns = BILLING_PARTY_TEMPLATE_HEADERS.map(() => ({ width: 22 }));

  const headerRow = sheet.getRow(1);
  BILLING_PARTY_TEMPLATE_HEADERS.forEach((header, index) => {
    const cell = headerRow.getCell(index + 1);
    cell.value = header;
    cell.font = { bold: true };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF2F2F2" } };
  });
}

/**
 * Builds and downloads the two-sheet `.xlsx` template: "Upload Data"
 * (headers only, for the user to fill in) and "Sample" (headers + one
 * realistic example row). No other sheets are added.
 */
export async function downloadBillingPartyUploadTemplate(): Promise<void> {
  const ExcelJS = (await import("exceljs")).default;
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Transjit Express TMS";
  workbook.created = new Date();

  writeHeaderRow(workbook.addWorksheet("Upload Data"));

  const sampleSheet = workbook.addWorksheet("Sample");
  writeHeaderRow(sampleSheet);
  const sampleRow = sampleSheet.getRow(2);
  BILLING_PARTY_TEMPLATE_HEADERS.forEach((header, index) => {
    sampleRow.getCell(index + 1).value = SAMPLE_ROW[header];
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "billing-party-master-upload-template.xlsx";
  link.click();
  URL.revokeObjectURL(url);
}

/**
 * Reads only the "Upload Data" sheet (the "Sample" sheet is always
 * ignored) and validates every row against the EXISTING Billing Party
 * Master rules: `validateBillingParty()` — the exact same schema the
 * Add/Edit Billing Party form already uses — plus the one real duplicate
 * rule this module already has (`code` must be unique, both within the
 * file and against currently existing billing parties). No new business
 * rule or second validation path is invented here.
 *
 * All-or-nothing: if any row fails, `rows` is returned empty so the
 * caller never imports a partial file.
 */
export async function parseAndValidateBillingPartyUpload(
  file: File,
  existingBillingParties: BillingPartyRecord[]
): Promise<BillingPartyUploadParseResult> {
  const ExcelJS = (await import("exceljs")).default;
  const workbook = new ExcelJS.Workbook();
  const buffer = await file.arrayBuffer();
  await workbook.xlsx.load(buffer);

  const sheet = workbook.getWorksheet("Upload Data");

  if (!sheet) {
    return {
      rows: [],
      errors: [
        {
          excelRow: 1,
          messages: ['Could not find an "Upload Data" sheet in this file. Please use the downloaded template.'],
        },
      ],
    };
  }

  const columnByHeader = new Map<string, number>();
  sheet.getRow(1).eachCell((cell, colNumber) => {
    const header = cellToString(cell.value);
    if (header) columnByHeader.set(header, colNumber);
  });

  const missingHeaders = BILLING_PARTY_TEMPLATE_HEADERS.filter((header) => !columnByHeader.has(header));

  if (missingHeaders.length > 0) {
    return {
      rows: [],
      errors: [
        {
          excelRow: 1,
          messages: [`Missing required column(s): ${missingHeaders.join(", ")}. Please use the downloaded template.`],
        },
      ],
    };
  }

  function cellValue(row: import("exceljs").Row, header: TemplateHeader): string {
    const colNumber = columnByHeader.get(header);
    return colNumber ? cellToString(row.getCell(colNumber).value) : "";
  }

  interface ParsedRow {
    excelRow: number;
    values: BillingPartyMaster;
    messages: string[];
  }

  const parsedRows: ParsedRow[] = [];
  const rowsByCode = new Map<string, number[]>();

  sheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber === 1) return; // header row

    const rawValues = BILLING_PARTY_TEMPLATE_HEADERS.map((header) => cellValue(row, header));
    const isBlankRow = rawValues.every((value) => value === "");
    if (isBlankRow) return;

    const code = cellValue(row, "Code");
    const name = cellValue(row, "Name");
    const gst = cellValue(row, "GST").toUpperCase();
    const mobile = cellValue(row, "Mobile");
    const email = cellValue(row, "Email");
    const city = cellValue(row, "City");
    const address = cellValue(row, "Address");
    const rawStatus = cellValue(row, "Status");
    const poNumber = cellValue(row, "PO Number");
    const concernPerson = cellValue(row, "Concern Person");
    const shortCode = cellValue(row, "Short Code").toUpperCase();
    const rawPaymentCycleDays = cellValue(row, "Payment Cycle Days");

    const messages: string[] = [];

    // Same default the Add Billing Party form already uses for a new record.
    let status: BillingPartyMaster["status"] = "Active";
    if (rawStatus) {
      const matched = BILLING_PARTY_STATUS_OPTIONS.find(
        (option) => option.toLowerCase() === rawStatus.toLowerCase()
      );
      if (!matched) {
        messages.push(`Status must be one of: ${BILLING_PARTY_STATUS_OPTIONS.join(", ")}.`);
      } else {
        status = matched;
      }
    }

    let paymentCycleDays = 0;
    if (rawPaymentCycleDays) {
      const parsed = Number(rawPaymentCycleDays);
      if (Number.isNaN(parsed)) {
        messages.push("Payment Cycle Days must be a number.");
      } else {
        paymentCycleDays = parsed;
      }
    }

    const candidate: BillingPartyMaster = {
      code,
      name,
      gst,
      mobile,
      email,
      city,
      address,
      status,
      entryStatus: "final",
      poNumber,
      concernPerson,
      shortCode,
      paymentCycleDays,
    };

    for (const message of Object.values(validateBillingParty(candidate))) {
      if (message) messages.push(message);
    }

    if (code) {
      if (existingBillingParties.some((existing) => existing.code === code)) {
        messages.push(`Code "${code}" already exists in Billing Party Master.`);
      }
      rowsByCode.set(code, [...(rowsByCode.get(code) ?? []), rowNumber]);
    }

    parsedRows.push({ excelRow: rowNumber, values: candidate, messages });
  });

  // In-file duplicate codes: every row sharing a non-blank code is
  // invalid, even if it otherwise passed every check above.
  for (const [code, rowNumbers] of rowsByCode) {
    if (rowNumbers.length <= 1) continue;

    const message = `Code "${code}" is used by more than one row in this file (rows ${rowNumbers.join(", ")}).`;
    for (const parsedRow of parsedRows) {
      if (rowNumbers.includes(parsedRow.excelRow)) parsedRow.messages.push(message);
    }
  }

  const errors: BillingPartyUploadRowError[] = parsedRows
    .filter((row) => row.messages.length > 0)
    .map((row) => ({ excelRow: row.excelRow, messages: row.messages }))
    .sort((a, b) => a.excelRow - b.excelRow);

  const rows: BillingPartyUploadRow[] =
    errors.length > 0
      ? []
      : parsedRows.map((row) => ({ excelRow: row.excelRow, values: row.values }));

  return { rows, errors };
}
