-- ==========================================================
-- Migration: 005_create_transporters
-- Module:    Transporter Master
-- Created:   Phase 10 (Transporter Master reference implementation)
--
-- Reference: components/transporter/transporter.schema.ts
--            components/services/transporter.service.ts
--
-- This file is a record of the schema change required by the
-- application. It is NOT executed automatically — run it manually
-- (or via your preferred migration tool) against the target Supabase
-- project before the Transporter Master module is used.
--
-- Notes:
--   - `transporter_type` and `preferred_payment_mode` are intentionally
--     left as plain text with app-level defaults, NOT database
--     enums/CHECK constraints. Per the locked Transporter Master
--     architecture, both must stay swappable for a future Transporter
--     Type Master / Vendor Payments integration without a schema
--     change.
--   - `payment_term` IS a CHECK constraint ('Immediate' / 'Credit') —
--     unlike Transporter Type, this is a fixed business rule (it
--     directly governs the Credit Days behavior), not a swappable
--     list.
--   - `transporter_code` is generated by the application
--     (`generateTransporterCode`) and is immutable after creation —
--     enforced at the application layer, not by a database trigger.
--   - Foreign keys are deliberately not included in this migration.
-- ==========================================================

create table if not exists public.transporters (
  id bigint generated always as identity primary key,

  -- Identity
  transporter_code text not null unique,
  transporter_name text not null,
  transporter_type text not null default 'Fleet Owner',
  gstin text not null default '',
  pan text not null default '',

  -- Contact
  contact_person text not null default '',
  mobile text not null default '',
  alternate_mobile text not null default '',
  email text not null default '',
  website text not null default '',

  -- Address
  address text not null default '',
  city text not null default '',
  state text not null default '',
  pincode text not null default '',

  -- Banking
  account_holder_name text not null default '',
  bank_name text not null default '',
  account_number text not null default '',
  ifsc text not null default '',
  upi_id text not null default '',

  -- Commercial
  payment_term text not null default 'Immediate'
    check (payment_term in ('Immediate', 'Credit')),
  credit_days integer not null default 0,
  credit_limit numeric not null default 0,
  preferred_payment_mode text not null default 'Bank Transfer',

  -- Additional
  remarks text not null default '',

  status text not null default 'Active'
    check (status in ('Active', 'Inactive')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_transporters_transporter_name on public.transporters (transporter_name);
create index if not exists idx_transporters_contact_person on public.transporters (contact_person);
create index if not exists idx_transporters_mobile on public.transporters (mobile);
create index if not exists idx_transporters_status on public.transporters (status);

-- Keeps `updated_at` current on every row update.
create or replace function public.set_transporters_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_transporters_updated_at on public.transporters;

create trigger trg_transporters_updated_at
before update on public.transporters
for each row
execute function public.set_transporters_updated_at();
