-- ==========================================================
-- Migration: 006_create_materials
-- Module:    Material Master
-- Created:   Phase 11 (Material Master reference implementation)
--
-- Reference: components/material/material.schema.ts
--            components/services/material.service.ts
--
-- This file is a record of the schema change required by the
-- application. It is NOT executed automatically — run it manually
-- (or via your preferred migration tool) against the target Supabase
-- project before the Material Master module is used.
--
-- Notes:
--   - `category` and `unit` are intentionally left as plain text with
--     no CHECK constraint — per the locked Material Master
--     architecture, both must stay swappable for a future Material
--     Category Master without a schema change.
--   - `material_code` is generated by the application
--     (`generateMaterialCode`, "MAT0001", "MAT0002", ...) and is
--     immutable after creation — enforced at the application layer,
--     not by a database trigger.
--   - Foreign keys are deliberately not included in this migration.
--   - This migration DOES seed starter data (unlike prior masters),
--     per explicit instruction — 78 materials across the 9 categories
--     that have starter records. "Electrical" is a valid selectable
--     category with no seed rows yet.
-- ==========================================================

create table if not exists public.materials (
  id bigint generated always as identity primary key,

  material_code text not null unique,
  material_name text not null,
  category text not null default '',
  hsn_code text not null default '',
  unit text not null default '',
  gst_percentage numeric not null default 0,
  description text not null default '',

  status text not null default 'Active'
    check (status in ('Active', 'Inactive')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_materials_material_name on public.materials (material_name);
create index if not exists idx_materials_category on public.materials (category);
create index if not exists idx_materials_hsn_code on public.materials (hsn_code);
create index if not exists idx_materials_status on public.materials (status);

-- Keeps `updated_at` current on every row update.
create or replace function public.set_materials_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_materials_updated_at on public.materials;

create trigger trg_materials_updated_at
before update on public.materials
for each row
execute function public.set_materials_updated_at();

-- ==========================================================
-- Seed Data — 78 starter materials across 9 categories.
-- HSN Code, Unit, and Description are left blank for the user to fill
-- in later; every row defaults to Active status.
-- ==========================================================

insert into public.materials (material_code, material_name, category) values
  -- Steel (15)
  ('MAT0001', 'TMT Bars', 'Steel'),
  ('MAT0002', 'Steel Coils', 'Steel'),
  ('MAT0003', 'Steel Sheets', 'Steel'),
  ('MAT0004', 'Steel Plates', 'Steel'),
  ('MAT0005', 'MS Pipe', 'Steel'),
  ('MAT0006', 'GI Pipe', 'Steel'),
  ('MAT0007', 'MS Angle', 'Steel'),
  ('MAT0008', 'MS Channel', 'Steel'),
  ('MAT0009', 'MS Beam', 'Steel'),
  ('MAT0010', 'Wire Rod', 'Steel'),
  ('MAT0011', 'Steel Scrap', 'Steel'),
  ('MAT0012', 'Iron Scrap', 'Steel'),
  ('MAT0013', 'Aluminium Sheets', 'Steel'),
  ('MAT0014', 'Aluminium Coil', 'Steel'),
  ('MAT0015', 'Copper Wire', 'Steel'),

  -- Cement (2)
  ('MAT0016', 'Cement', 'Cement'),
  ('MAT0017', 'Fly Ash', 'Cement'),

  -- Construction (14)
  ('MAT0018', 'Bricks', 'Construction'),
  ('MAT0019', 'Cement Blocks', 'Construction'),
  ('MAT0020', 'AAC Blocks', 'Construction'),
  ('MAT0021', 'Sand', 'Construction'),
  ('MAT0022', 'M-Sand', 'Construction'),
  ('MAT0023', 'Blue Metal', 'Construction'),
  ('MAT0024', 'Aggregate', 'Construction'),
  ('MAT0025', 'Gravel', 'Construction'),
  ('MAT0026', 'Stone Chips', 'Construction'),
  ('MAT0027', 'Granite', 'Construction'),
  ('MAT0028', 'Marble', 'Construction'),
  ('MAT0029', 'Tiles', 'Construction'),
  ('MAT0030', 'Plywood', 'Construction'),
  ('MAT0031', 'Glass Sheets', 'Construction'),

  -- Machinery (11)
  ('MAT0032', 'Machinery', 'Machinery'),
  ('MAT0033', 'Machine Parts', 'Machinery'),
  ('MAT0034', 'Industrial Equipment', 'Machinery'),
  ('MAT0035', 'Electrical Equipment', 'Machinery'),
  ('MAT0036', 'Electrical Cables', 'Machinery'),
  ('MAT0037', 'Transformers', 'Machinery'),
  ('MAT0038', 'Motors', 'Machinery'),
  ('MAT0039', 'Pumps', 'Machinery'),
  ('MAT0040', 'Bearings', 'Machinery'),
  ('MAT0041', 'Valves', 'Machinery'),
  ('MAT0042', 'Hardware Items', 'Machinery'),

  -- Agriculture (9)
  ('MAT0043', 'Rice', 'Agriculture'),
  ('MAT0044', 'Wheat', 'Agriculture'),
  ('MAT0045', 'Maize', 'Agriculture'),
  ('MAT0046', 'Cotton', 'Agriculture'),
  ('MAT0047', 'Sugar', 'Agriculture'),
  ('MAT0048', 'Fertilizer', 'Agriculture'),
  ('MAT0049', 'Seeds', 'Agriculture'),
  ('MAT0050', 'Animal Feed', 'Agriculture'),
  ('MAT0051', 'Pulses', 'Agriculture'),

  -- Chemicals (6)
  ('MAT0052', 'Chemicals', 'Chemicals'),
  ('MAT0053', 'Paint', 'Chemicals'),
  ('MAT0054', 'Solvents', 'Chemicals'),
  ('MAT0055', 'Lubricants', 'Chemicals'),
  ('MAT0056', 'Bitumen', 'Chemicals'),
  ('MAT0057', 'Resin', 'Chemicals'),

  -- FMCG (7)
  ('MAT0058', 'Packaged Goods', 'FMCG'),
  ('MAT0059', 'Food Products', 'FMCG'),
  ('MAT0060', 'Beverages', 'FMCG'),
  ('MAT0061', 'Paper Rolls', 'FMCG'),
  ('MAT0062', 'Plastic Granules', 'FMCG'),
  ('MAT0063', 'Plastic Products', 'FMCG'),
  ('MAT0064', 'Packaging Material', 'FMCG'),

  -- Textile (4)
  ('MAT0065', 'Cotton Bales', 'Textile'),
  ('MAT0066', 'Yarn', 'Textile'),
  ('MAT0067', 'Fabric', 'Textile'),
  ('MAT0068', 'Garments', 'Textile'),

  -- Miscellaneous (10)
  ('MAT0069', 'Furniture', 'Miscellaneous'),
  ('MAT0070', 'Household Goods', 'Miscellaneous'),
  ('MAT0071', 'Automobile Parts', 'Miscellaneous'),
  ('MAT0072', 'Tyres', 'Miscellaneous'),
  ('MAT0073', 'Batteries', 'Miscellaneous'),
  ('MAT0074', 'LPG Cylinders', 'Miscellaneous'),
  ('MAT0075', 'Empty Containers', 'Miscellaneous'),
  ('MAT0076', 'Wooden Logs', 'Miscellaneous'),
  ('MAT0077', 'Bamboo', 'Miscellaneous'),
  ('MAT0078', 'Miscellaneous Goods', 'Miscellaneous')
on conflict (material_code) do nothing;
