import {
  validateMaterial,
  MATERIAL_CATEGORY_OPTIONS,
  MATERIAL_STATUS_OPTIONS,
  MATERIAL_UNIT_OPTIONS,
  type Material,
} from "./material.schema";
import type { MaterialRecord } from "@/components/services/material.service";

/**
 * The exact Material Master columns, in the same order/labels already
 * used by MaterialListPage.tsx's existing CSV Export (`handleExport`) —
 * the app's own established definition of "the Material Master columns".
 * No field is invented here.
 */
export const MATERIAL_TEMPLATE_HEADERS = [
  "Material Code",
  "Material Name",
  "Category",
  "HSN Code",
  "Unit",
  "GST Percentage",
  "Description",
  "Status",
] as const;

type TemplateHeader = (typeof MATERIAL_TEMPLATE_HEADERS)[number];

/** One realistic example row for the "Sample" sheet. `Material Code` is
 * left blank, matching the existing Add Material form: `code` is never
 * manually typed anywhere in this app — it's auto-generated by
 * `createMaterial()` (see material.service.ts) when left blank. */
const SAMPLE_ROW: Record<TemplateHeader, string> = {
  "Material Code": "",
  "Material Name": "TMT Steel Bars",
  Category: "Steel",
  "HSN Code": "7214",
  Unit: "TON",
  "GST Percentage": "18",
  Description: "12mm TMT steel bars",
  Status: "Active",
};

export interface MaterialUploadRow {
  /** 1-based row number as it appears in the Excel sheet (row 1 is the header). */
  excelRow: number;
  values: Material;
}

export interface MaterialUploadRowError {
  excelRow: number;
  messages: string[];
}

export interface MaterialUploadParseResult {
  rows: MaterialUploadRow[];
  errors: MaterialUploadRowError[];
}

function cellToString(value: unknown): string {
  if (value == null) return "";

  if (typeof value === "object") {
    const text = (value as { text?: unknown }).text;
    if (typeof text === "string") return text.trim();

    const result = (value as { result?: unknown }).result;
    if (result != null) return String(result).trim();

    return "";
  }

  return String(value).trim();
}

function writeHeaderRow(sheet: import("exceljs").Worksheet) {
  sheet.columns = MATERIAL_TEMPLATE_HEADERS.map(() => ({ width: 22 }));

  const headerRow = sheet.getRow(1);
  MATERIAL_TEMPLATE_HEADERS.forEach((header, index) => {
    const cell = headerRow.getCell(index + 1);
    cell.value = header;
    cell.font = { bold: true };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF2F2F2" } };
  });
}

/**
 * Builds and downloads the two-sheet `.xlsx` template: "Upload Data"
 * (headers only, for the user to fill in) and "Sample" (headers + one
 * realistic example row). No other sheets are added.
 */
export async function downloadMaterialUploadTemplate(): Promise<void> {
  const ExcelJS = (await import("exceljs")).default;
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Transjit Express TMS";
  workbook.created = new Date();

  writeHeaderRow(workbook.addWorksheet("Upload Data"));

  const sampleSheet = workbook.addWorksheet("Sample");
  writeHeaderRow(sampleSheet);
  const sampleRow = sampleSheet.getRow(2);
  MATERIAL_TEMPLATE_HEADERS.forEach((header, index) => {
    sampleRow.getCell(index + 1).value = SAMPLE_ROW[header];
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "material-master-upload-template.xlsx";
  link.click();
  URL.revokeObjectURL(url);
}

/**
 * Reads only the "Upload Data" sheet (the "Sample" sheet is always
 * ignored) and validates every row against the EXISTING Material Master
 * rules: `validateMaterial()` — the exact same schema the Add/Edit
 * Material form already uses — plus the one real duplicate rule this
 * module already has (`code`/"Material Code" must be unique, both within
 * the file and against currently existing materials). No new business
 * rule or second validation path is invented here.
 *
 * All-or-nothing: if any row fails, `rows` is returned empty so the
 * caller never imports a partial file.
 */
export async function parseAndValidateMaterialUpload(
  file: File,
  existingMaterials: MaterialRecord[]
): Promise<MaterialUploadParseResult> {
  const ExcelJS = (await import("exceljs")).default;
  const workbook = new ExcelJS.Workbook();
  const buffer = await file.arrayBuffer();
  await workbook.xlsx.load(buffer);

  const sheet = workbook.getWorksheet("Upload Data");

  if (!sheet) {
    return {
      rows: [],
      errors: [
        {
          excelRow: 1,
          messages: ['Could not find an "Upload Data" sheet in this file. Please use the downloaded template.'],
        },
      ],
    };
  }

  const columnByHeader = new Map<string, number>();
  sheet.getRow(1).eachCell((cell, colNumber) => {
    const header = cellToString(cell.value);
    if (header) columnByHeader.set(header, colNumber);
  });

  const missingHeaders = MATERIAL_TEMPLATE_HEADERS.filter((header) => !columnByHeader.has(header));

  if (missingHeaders.length > 0) {
    return {
      rows: [],
      errors: [
        {
          excelRow: 1,
          messages: [`Missing required column(s): ${missingHeaders.join(", ")}. Please use the downloaded template.`],
        },
      ],
    };
  }

  function cellValue(row: import("exceljs").Row, header: TemplateHeader): string {
    const colNumber = columnByHeader.get(header);
    return colNumber ? cellToString(row.getCell(colNumber).value) : "";
  }

  interface ParsedRow {
    excelRow: number;
    values: Material;
    messages: string[];
  }

  const parsedRows: ParsedRow[] = [];
  const rowsByCode = new Map<string, number[]>();

  sheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber === 1) return; // header row

    const rawValues = MATERIAL_TEMPLATE_HEADERS.map((header) => cellValue(row, header));
    const isBlankRow = rawValues.every((value) => value === "");
    if (isBlankRow) return;

    const code = cellValue(row, "Material Code");
    const materialName = cellValue(row, "Material Name");
    const rawCategory = cellValue(row, "Category");
    const hsnCode = cellValue(row, "HSN Code");
    const rawUnit = cellValue(row, "Unit");
    const rawGstPercentage = cellValue(row, "GST Percentage");
    const description = cellValue(row, "Description");
    const rawStatus = cellValue(row, "Status");

    const messages: string[] = [];

    // Category and Unit are optional controlled values in the existing
    // schema — an unrecognized non-blank value is invalid, but blank is fine.
    let category = rawCategory;
    if (rawCategory) {
      const matched = MATERIAL_CATEGORY_OPTIONS.find(
        (option) => option.toLowerCase() === rawCategory.toLowerCase()
      );
      if (!matched) {
        messages.push(`Category must be one of: ${MATERIAL_CATEGORY_OPTIONS.join(", ")} (or left blank).`);
      } else {
        category = matched;
      }
    }

    let unit = rawUnit;
    if (rawUnit) {
      const matched = MATERIAL_UNIT_OPTIONS.find(
        (option) => option.toLowerCase() === rawUnit.toLowerCase()
      );
      if (!matched) {
        messages.push(`Unit must be one of: ${MATERIAL_UNIT_OPTIONS.join(", ")} (or left blank).`);
      } else {
        unit = matched;
      }
    }

    // Same default the Add Material form already uses for a new record.
    let status: Material["status"] = "Active";
    if (rawStatus) {
      const matched = MATERIAL_STATUS_OPTIONS.find(
        (option) => option.toLowerCase() === rawStatus.toLowerCase()
      );
      if (!matched) {
        messages.push(`Status must be one of: ${MATERIAL_STATUS_OPTIONS.join(", ")}.`);
      } else {
        status = matched;
      }
    }

    let gstPercentage = 0;
    if (rawGstPercentage) {
      const parsed = Number(rawGstPercentage);
      if (Number.isNaN(parsed)) {
        messages.push("GST Percentage must be a number.");
      } else {
        gstPercentage = parsed;
      }
    }

    const candidate: Material = {
      code,
      materialName,
      category,
      hsnCode,
      unit,
      gstPercentage,
      description,
      status,
    };

    for (const message of Object.values(validateMaterial(candidate))) {
      if (message) messages.push(message);
    }

    if (code) {
      if (existingMaterials.some((existing) => existing.code === code)) {
        messages.push(`Material Code "${code}" already exists in Material Master.`);
      }
      rowsByCode.set(code, [...(rowsByCode.get(code) ?? []), rowNumber]);
    }

    parsedRows.push({ excelRow: rowNumber, values: candidate, messages });
  });

  // In-file duplicate codes: every row sharing a non-blank code is
  // invalid, even if it otherwise passed every check above.
  for (const [code, rowNumbers] of rowsByCode) {
    if (rowNumbers.length <= 1) continue;

    const message = `Material Code "${code}" is used by more than one row in this file (rows ${rowNumbers.join(", ")}).`;
    for (const parsedRow of parsedRows) {
      if (rowNumbers.includes(parsedRow.excelRow)) parsedRow.messages.push(message);
    }
  }

  const errors: MaterialUploadRowError[] = parsedRows
    .filter((row) => row.messages.length > 0)
    .map((row) => ({ excelRow: row.excelRow, messages: row.messages }))
    .sort((a, b) => a.excelRow - b.excelRow);

  const rows: MaterialUploadRow[] =
    errors.length > 0
      ? []
      : parsedRows.map((row) => ({ excelRow: row.excelRow, values: row.values }));

  return { rows, errors };
}
